name: DB Workflow

on:
  push:
    branches: [main]
    paths:
      - 'DB/**'
  pull_request:
    branches: [main]
    paths:
      - 'DB/**'
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag patrickpilotti/db-biztrips:${{ github.sha }}
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}