name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    #enter backend and then edelfiles where the Dockerfile is located
      working-directory: ./backend/edelfiles
      run: docker build . --file Dockerfile --tag biztrips-backend:$(date +%s)