name: Frontend Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: docker build -t patrickpilotti/biztrips-frontend:${{ github.sha }} .

  push-job:
    runs-on: ubuntu-latest
    needs: build-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_SECRET }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: docker push patrickpilotti/biztrips-frontend:${{ github.sha }}