name: Frontend Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:
    branches:
      - main

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend Docker image
        working-directory: ./frontend
        run: |
          docker build . --file Dockerfile --tag patrickpilotti/biztrips-frontend:${{ github.sha }}

      - name: Push Frontend Docker image
        run: |
          docker push patrickpilotti/biztrips-frontend:${{ github.sha }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'